import { builtinModules } from "node:module";
import { copyFileSync } from "node:fs";
import esbuild from "esbuild";
import process from "node:process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outfile = prod ? "main.js" : "dist/main.js";

const copyPlugin = {
	name: "copy-to-dist",
	setup(build) {
		build.onEnd(() => {
			copyFileSync("manifest.json", "dist/manifest.json");
			copyFileSync("styles.css", "dist/styles.css");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	plugins: prod ? [] : [copyPlugin],
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
